//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace StockAnalyzerWB {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(3)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class Sheet3 : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        internal Microsoft.Office.Tools.Excel.NamedRange Sheet3_Ask;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Sheet3_Bid;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Sheet3_Break_Even;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Sheet3_Last;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Sheet3_LastPrice;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Sheet3_Open_Interest;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Sheet3_Price;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Sheet3_Strike_Price;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Sheet3_Symbol;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Sheet3_Vol;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Sheet3_xAsk;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Sheet3_xBid;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Sheet3(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Sheet3", "Sheet3") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.Sheet3 = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.Sheet3_Ask.BeginInit();
            this.Sheet3_Bid.BeginInit();
            this.Sheet3_Break_Even.BeginInit();
            this.Sheet3_Last.BeginInit();
            this.Sheet3_LastPrice.BeginInit();
            this.Sheet3_Open_Interest.BeginInit();
            this.Sheet3_Price.BeginInit();
            this.Sheet3_Strike_Price.BeginInit();
            this.Sheet3_Symbol.BeginInit();
            this.Sheet3_Vol.BeginInit();
            this.Sheet3_xAsk.BeginInit();
            this.Sheet3_xBid.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.Sheet3_xBid.EndInit();
            this.Sheet3_xAsk.EndInit();
            this.Sheet3_Vol.EndInit();
            this.Sheet3_Symbol.EndInit();
            this.Sheet3_Strike_Price.EndInit();
            this.Sheet3_Price.EndInit();
            this.Sheet3_Open_Interest.EndInit();
            this.Sheet3_LastPrice.EndInit();
            this.Sheet3_Last.EndInit();
            this.Sheet3_Break_Even.EndInit();
            this.Sheet3_Bid.EndInit();
            this.Sheet3_Ask.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.Sheet3_Ask = Globals.Factory.CreateNamedRange(null, null, "Sheet3!Ask", "Sheet3_Ask", this);
            this.Sheet3_Bid = Globals.Factory.CreateNamedRange(null, null, "Sheet3!Bid", "Sheet3_Bid", this);
            this.Sheet3_Break_Even = Globals.Factory.CreateNamedRange(null, null, "Sheet3!Break_Even", "Sheet3_Break_Even", this);
            this.Sheet3_Last = Globals.Factory.CreateNamedRange(null, null, "Sheet3!Last", "Sheet3_Last", this);
            this.Sheet3_LastPrice = Globals.Factory.CreateNamedRange(null, null, "Sheet3!LastPrice", "Sheet3_LastPrice", this);
            this.Sheet3_Open_Interest = Globals.Factory.CreateNamedRange(null, null, "Sheet3!Open_Interest", "Sheet3_Open_Interest", this);
            this.Sheet3_Price = Globals.Factory.CreateNamedRange(null, null, "Sheet3!Price", "Sheet3_Price", this);
            this.Sheet3_Strike_Price = Globals.Factory.CreateNamedRange(null, null, "Sheet3!Strike_Price", "Sheet3_Strike_Price", this);
            this.Sheet3_Symbol = Globals.Factory.CreateNamedRange(null, null, "Sheet3!Symbol", "Sheet3_Symbol", this);
            this.Sheet3_Vol = Globals.Factory.CreateNamedRange(null, null, "Sheet3!Vol", "Sheet3_Vol", this);
            this.Sheet3_xAsk = Globals.Factory.CreateNamedRange(null, null, "Sheet3!xAsk", "Sheet3_xAsk", this);
            this.Sheet3_xBid = Globals.Factory.CreateNamedRange(null, null, "Sheet3!xBid", "Sheet3_xBid", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.Sheet3_xBid.Dispose();
            this.Sheet3_xAsk.Dispose();
            this.Sheet3_Vol.Dispose();
            this.Sheet3_Symbol.Dispose();
            this.Sheet3_Strike_Price.Dispose();
            this.Sheet3_Price.Dispose();
            this.Sheet3_Open_Interest.Dispose();
            this.Sheet3_LastPrice.Dispose();
            this.Sheet3_Last.Dispose();
            this.Sheet3_Break_Even.Dispose();
            this.Sheet3_Bid.Dispose();
            this.Sheet3_Ask.Dispose();
            base.OnShutdown();
        }
    }
    
    internal sealed partial class Globals {
        
        private static Sheet3 _Sheet3;
        
        internal static Sheet3 Sheet3 {
            get {
                return _Sheet3;
            }
            set {
                if ((_Sheet3 == null)) {
                    _Sheet3 = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
